data = [
        {'title': 'The Shawshank Redemption',
        'image': 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',
        'description': 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
        'release': "1989-01-19",
        'rating': 9.2,
        'category': 'drama',
        },
        {'title': 'The Dark Knight',
        'image': 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg',
        'description': 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
        'release': "2008-09-12",
        'rating': 9.0,
        'category': 'action',
        },
        {'title': 'The Matrix',
        'image': 'https://flxt.tmsimg.com/assets/p22804_p_v8_av.jpg',
        'description': 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
        'release': "1999-07-11",
        'rating': 8.7,
        'category': 'sci-fi'
        },
        {'title': 'Interstellar',
        'image': 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
        'description': 'A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.',
        'release': "2014-07-21",
        'rating': 8.6,
        'category': 'comady',
        },
        {'title': 'WALL·E',
        'image': 'https://lumiere-a.akamaihd.net/v1/images/p_walle_19753_69f7ff00.jpeg',
        'description': 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.',
        'release': "2020-07-01",
        'rating': 8.4,
        'category': 'romantic',
        },
        # {'title': '',
        #  'image': '',
        #  'description': '',
        #  'release': '',
        #  'rating': '',
        #  'category': '',
        #  },
        # {'title': '',
        #  'image': '',
        #  'description': '',
        #  'release': '',
        #  'rating': '',
        #  'category': '',
        #  },
        

]
